# Use Trusty Tahr (Ubuntu 14.04 LTS)
dist: trusty
sudo: false

# C++ builds with clang and gcc
language: cpp
compiler:
    - clang
    - gcc

# Configure, build and run.
script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ../cmake && cmake --build . && echo "-1" | ./sg14
